version: '3.8'
services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  blackjack-api:
    image: blackjack-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/blackjackDB
    depends_on:
      - mongo
volumes:
  mongo-data: